pipeline{
    agent{
        dockerfile true
    }
    stages{
        stage("Installing dependencies"){
            sh'''
            npm install
            '''
        }
        stage("Running and testing frontend"){
            sh'''
            npm start
            '''
        }
    }
}