pipeline{
    agent{
        dockerfile true
    }
    stages{
        stage("Installing dependencies"){
            steps{
                sh'''
                npm install
                '''
            }
        }
        stage("Running and testing frontend"){
            steps{
                sh'''
                npm start
                '''
            }
        }
    }
}