pipeline{
    agent{
        
    }
    stages{
        stage("Installing dependencies"){
            steps{
                sh'''
                npm install
                '''
            }
        }
        stage("Checking Backend"){
            steps{
                sh'''
                node server.js
                '''
            }
        }
    }
}