apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: harish00006/devops-dashboard-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-dashboard
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
