services:
  jenkins:
    build:
      context: ..
      dockerfile: jenkins/Dockerfile
    container_name: devops-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      KUBECONFIG: /var/jenkins_home/.kube/config
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - ${USERPROFILE}/.kube:/var/jenkins_home/.kube:ro
    restart: unless-stopped

volumes:
  jenkins_home:
